platform :ios, '7.0'
pod ‘CYLTabBarController’
pod  'AVOSCloud'
pod  'AVOSCloudIM'
pod  'CYLDeallocBlockExecutor'
pod  'IQKeyboardManager'
pod  'JSONModel'
pod  'XHSetting'
pod  'MBProgressHUD'
pod  'MJRefresh'
pod 'TTTAttributedLabel'
pod 'SDWebImage'
pod 'DateTools'
pod 'FXForms'
